default: &default
  :delivery_method: :smtp
  :smtp_settings:
    :address: 'smtp.cmb.com'
    :port: 25
    :domain: 'cmb.com'
    :user_name: 'anti-phishing@cmb.com'
    :password: ''
    :authentication: 'login'
    :enable_starttls_auto: true

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  :smtp_settings:
    :password: <%= ENV['SMTP_PASSWORD'] %>