default: &default
  :delivery_method: :smtp
  :smtp_settings:
    :address: 'smtp.126.com'
    :port: 25
    :domain: '126.com'
    :user_name: 'bromine@126.com'
    :password: 'bromine0x23'
    :authentication: 'login'
    :enable_starttls_auto: true

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  :smtp_settings:
    :password: <%= ENV['SMTP_PASSWORD'] %>